M48
; DRILL file {KiCad 6.99.0-unknown-455e330f3b~148~ubuntu20.04.1} date Tue Mar 15 10:42:58 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-15T10:42:58+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.99.0-unknown-455e330f3b~148~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X17.0Y31.25
X57.0Y2.75
T0
M30
